dist: xenial
language: python
cache: pip

matrix:
  include:
  - name: "Test Python27"
    python: "2.7"
    env: TOXENV=py27
  - name: "Test Python36"
    python: "3.6"
    env: TOXENV=py36
  - name: "Test Python37"
    python: "3.7"
    env: TOXENV=py37

install:
  - pip install tox

script:
  tox
